#!/usr/bin/env bash
#
# 02_apply_public_ingress_prod.sh
#
# Creates the public ALB by applying the two Ingress objects in
# ingress-public.yaml, after substituting the certificate ARN and the source
# IP ranges allowed to reach it.
#
# The ALB is not created by this script directly -- the AWS Load Balancer
# Controller (installed in 07_) watches for these Ingress objects and builds
# the load balancer, listener, target groups and security group from them.
# Deleting the Ingress deletes the ALB.
#
# Usage:
#   ./02_apply_public_ingress_prod.sh 203.0.113.5/32      # apply, allow one IP
#   ./02_apply_public_ingress_prod.sh                     # apply, reuse saved CIDRs
#   ./02_apply_public_ingress_prod.sh dns                 # print the DNS records to add
#   ./02_apply_public_ingress_prod.sh verify              # state of ALB, targets, DNS
#   ./02_apply_public_ingress_prod.sh delete              # remove Ingress (and the ALB)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REGION="ap-southeast-1"
CLUSTER_NAME="data-platform-prod"   # used to find the VPC's NAT gateway, below
MANIFEST="$SCRIPT_DIR/ingress-public.yaml"
PRIMARY_DOMAIN="trino.nopega.net"
GROUP_NAME="data-platform-public"
CIDR_FILE="$SCRIPT_DIR/.inbound-cidrs"   # gitignored; environment-specific
RECORDS_FILE="$SCRIPT_DIR/alb-dns-records.txt"
ZONE="nopega.net"
SM_CF_TOKEN="data-platform-prod-cloudflare-dns-token"
MODE="${1:-}"

need() { command -v "$1" >/dev/null 2>&1 || { echo "ERROR: '$1' not found in PATH." >&2; exit 1; }; }
need kubectl; need aws; need dig

alb_hostname() {
  # Either Ingress reports the same address -- they share one ALB.
  kubectl get ingress trino-public -n data-platform \
    -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true
}


# Write the Cloudflare import file from the Ingress manifest and the live ALB
# hostname.
#
# GENERATED, never hand-edited. The hand-edited version fell behind twice: when
# grafana was added it was updated, when argocd was added it was updated, and
# when prometheus was added it was not -- so the import silently added nothing
# and the host resolved to nowhere. Every input is already known here: the
# hostnames come from the manifest that defines them, and the target comes from
# the load balancer that exists.
#
# A host is included only if this manifest actually routes it. A name on the
# certificate with no Ingress rule would resolve correctly and return 404 from
# the ALB's default action, which reads like a broken deployment rather than an
# absent one -- so those are listed as commented rows instead.
write_dns_records_file() {
  local host="$1" hosts ns existing_target
  hosts="$(grep -oE '^\s+- host:\s+\S+' "$MANIFEST" | awk '{print $3}')"
  {
    cat <<EOF
; Public hostnames pointing at the shared ALB.
;
; GENERATED by 02_apply_public_ingress_prod.sh -- do not edit by hand.
; ALB: ${host}
;
; HOW TO IMPORT
;   Cloudflare -> nopega.net -> DNS -> Records -> Import
;   Leave "Proxy imported DNS records" UNCHECKED.
;
; WHY DNS-ONLY AND NOT PROXIED
;   1. The ALB serves an ACM certificate issued for these exact names. Proxying
;      puts Cloudflare's certificate in front instead and adds a second TLS hop
;      that has to be configured correctly or it fails as a 5xx that looks like
;      the origin is down.
;   2. Cloudflare's free plan caps request bodies at 100 MB -- invisible for
;      Airflow, fatal for pushing a container image layer.
;
; A CNAME rather than an A record because an ALB's addresses change without
; notice. Pinning an IP works until AWS replaces a node, then fails.
;
; Every row points at the same load balancer. That is the point of the shared
; group.name: one ALB, one certificate, one bill, many hostnames routed by host
; rule.
;
; Cloudflare reports anything already present as a duplicate and skips it, so
; re-importing the whole file is safe.
;
; Do NOT delete the ACM validation CNAMEs also in this zone. ACM re-reads them
; to renew the certificate automatically.
;
; TTL 1 means "automatic" to Cloudflare.

EOF
    # Only rows the zone does NOT already have. Cloudflare's import treats a
    # duplicate row as an error rather than skipping it, and an import
    # containing errors has twice now failed to add the rows that were NOT
    # duplicates -- grafana the first time, prometheus the second. A file with
    # nothing but new rows imports cleanly or fails loudly, with no third
    # state.
    #
    # The check asks the zone's own nameserver, so a resolver's negative cache
    # cannot make an existing record look missing.
    ns="$(dig +short NS nopega.net 2>/dev/null | head -1)"
    for h in $hosts; do
      existing_target="$(dig +short CNAME "$h" ${ns:+@"$ns"} 2>/dev/null | head -1)"
      if [ -z "$existing_target" ]; then
        printf '%s.\t1\tIN\tCNAME\t%s.\n' "$h" "$host"
      elif [ "$existing_target" = "${host}." ]; then
        printf '; %s already in the zone, pointing at this ALB -- omitted\n' "$h"
      else
        printf '; %s ALREADY EXISTS but points at %s\n' "$h" "$existing_target"
        printf ';   NOT overwritten. If that is stale, fix it in the dashboard.\n'
      fi
    done
    cat <<'EOF'

; Names on the certificate that have no Ingress rule yet are NOT listed above.
; Pointing DNS at the ALB before a rule exists returns 404 from the default
; action, which reads like a broken deployment. Add the host rule first, re-run
; this script, and the row appears here on its own.
EOF
  } > "$RECORDS_FILE"
}


# ---------------------------------------------------------------------------
# Cloudflare DNS, via the API instead of zone-file import.
#
# The import path failed silently three times on this project: a file
# containing rows Cloudflare considered duplicates reported errors for those
# AND quietly dropped the rows that were new -- grafana once, prometheus
# twice. An API call per record either succeeds, or fails with a message that
# names the reason. There is no third state.
#
# The token is scoped to editing DNS in one zone, stored in Secrets Manager
# like every other credential here, prompted for once, and never in git.
# ---------------------------------------------------------------------------
cf_token() {
  if [ -n "${CLOUDFLARE_API_TOKEN:-}" ]; then
    printf '%s' "$CLOUDFLARE_API_TOKEN"; return
  fi
  local t
  t="$(aws secretsmanager get-secret-value --region "$REGION" \
    --secret-id "$SM_CF_TOKEN" --query SecretString --output text 2>/dev/null || true)"
  if [ -n "$t" ] && [ "$t" != "None" ]; then
    printf '%s' "$t"; return
  fi
  echo "" >&2
  echo "A Cloudflare API token is needed (once). Create it at:" >&2
  echo "  dash.cloudflare.com -> My Profile -> API Tokens -> Create Token" >&2
  echo "  -> template 'Edit zone DNS' -> Zone Resources: ${ZONE}" >&2
  printf 'Paste the token (input hidden): ' >&2
  read -rs t; echo "" >&2
  [ -n "$t" ] || { echo "ERROR: empty token." >&2; return 1; }
  if aws secretsmanager describe-secret --region "$REGION" --secret-id "$SM_CF_TOKEN" >/dev/null 2>&1; then
    aws secretsmanager put-secret-value --region "$REGION" \
      --secret-id "$SM_CF_TOKEN" --secret-string "$t" >/dev/null
  else
    aws secretsmanager create-secret --region "$REGION" --name "$SM_CF_TOKEN" \
      --description "Cloudflare API token scoped to DNS edits in ${ZONE}" \
      --secret-string "$t" >/dev/null
  fi
  echo "      stored in Secrets Manager as ${SM_CF_TOKEN}" >&2
  printf '%s' "$t"
}

cf_api() {
  local method="$1" path="$2" body="${3:-}"
  if [ -n "$body" ]; then
    curl -sS -X "$method" "https://api.cloudflare.com/client/v4${path}" \
      -H "Authorization: Bearer ${CF_TOKEN}" -H "Content-Type: application/json" \
      --data "$body"
  else
    curl -sS -X "$method" "https://api.cloudflare.com/client/v4${path}" \
      -H "Authorization: Bearer ${CF_TOKEN}"
  fi
}

# Create or verify one CNAME. Prints what it did; refuses to overwrite a
# record that points somewhere else, because that is a decision, not a sync.
cf_ensure_cname() {
  local name="$1" target="$2" existing
  existing="$(cf_api GET "/zones/${CF_ZONE_ID}/dns_records?type=CNAME&name=${name}" \
    | python3 -c "
import json,sys
r=json.load(sys.stdin).get('result') or []
print(r[0]['content'] if r else '')")"
  if [ "$existing" = "$target" ]; then
    echo "      ok        ${name} (already correct)"
    return 0
  fi
  if [ -n "$existing" ]; then
    echo "      SKIPPED   ${name} points at ${existing}"
    echo "                not overwritten -- fix it in the dashboard if stale"
    return 0
  fi
  local resp ok errs
  resp="$(cf_api POST "/zones/${CF_ZONE_ID}/dns_records" \
    "{\"type\":\"CNAME\",\"name\":\"${name}\",\"content\":\"${target}\",\"ttl\":1,\"proxied\":false}")"
  ok="$(printf '%s' "$resp" | python3 -c "import json,sys; print(json.load(sys.stdin).get('success'))")"
  if [ "$ok" = "True" ]; then
    echo "      CREATED   ${name} -> ${target}  (DNS only)"
  else
    errs="$(printf '%s' "$resp" | python3 -c "
import json,sys
print('; '.join(e.get('message','?') for e in json.load(sys.stdin).get('errors',[])))")"
    echo "      FAILED    ${name}: ${errs}" >&2
    return 1
  fi
}


# Prove the endpoints actually serve, without trusting the local resolver.
#
# WHY --resolve
# ---------------
# A record created seconds ago is live at the nameservers long before the
# resolver on this machine will admit it: having answered NXDOMAIN while the
# record was absent, it caches that for the zone's SOA minimum -- 1800s here.
# So `curl https://host/...` prints nothing and reads exactly like a broken
# deployment, while the deployment is fine.
#
# --resolve pins the hostname to the ALB's address for this one request,
# skipping DNS entirely. TLS still validates against the real hostname via SNI,
# so a certificate that does not cover the name still fails -- which is the
# thing worth checking.
#
# The path per host comes from the healthcheck-path annotation in the manifest.
# Those are already chosen to answer 200 without a session; duplicating them
# here would be a second list to keep in step.
check_endpoints() {
  local alb="$1" ip pairs host path code ns dns_ok
  ip="$(dig +short A "$alb" 2>/dev/null | head -1)"
  [ -n "$ip" ] || { echo "      cannot resolve the ALB itself; skipping" >&2; return 0; }
  ns="$(dig +short NS "$ZONE" 2>/dev/null | head -1)"

  pairs="$(python3 - "$MANIFEST" <<'PYEOF'
import sys, yaml
for d in yaml.safe_load_all(open(sys.argv[1])):
    if not d:
        continue
    host = d["spec"]["rules"][0]["host"]
    path = d["metadata"]["annotations"].get(
        "alb.ingress.kubernetes.io/healthcheck-path", "/")
    print(f"{host} {path}")
PYEOF
)"

  echo ""
  echo "      endpoint checks (DNS bypassed, TLS still verified)"
  printf '      %-24s %-18s %s\n' "HOST" "VIA ALB" "PUBLIC DNS"
  while read -r host path; do
    [ -n "$host" ] || continue
    code="$(curl -sI --max-time 15 --resolve "${host}:443:${ip}" \
      "https://${host}${path}" 2>/dev/null | awk 'NR==1{print $2}')"
    dns_ok="$(dig +short CNAME "$host" @1.1.1.1 2>/dev/null | head -1)"
    printf '      %-24s %-18s %s\n' \
      "$host" "${code:-no answer}" "$([ -n "$dns_ok" ] && echo resolving || echo "not yet")"
  done <<< "$pairs"

  cat <<EOF

      VIA ALB is the truth about the platform: 200 means the certificate,
      the listener rule and the target group are all correct for that host.

      PUBLIC DNS "not yet" next to a 200 is a resolver still holding the
      NXDOMAIN it cached while the record was absent. It clears by itself
      within the zone's SOA minimum -- 1800s for ${ZONE} -- and needs no
      action. The record is already live at ${ns:-the nameservers}.
EOF
}

cf_apply_dns() {
  local host="$1" hosts ns fail=0
  hosts="$(grep -oE '^\s+- host:\s+\S+' "$MANIFEST" | awk '{print $3}')"
  CF_TOKEN="$(cf_token)" || return 1
  CF_ZONE_ID="$(cf_api GET "/zones?name=${ZONE}" | python3 -c "
import json,sys
r=json.load(sys.stdin).get('result') or []
print(r[0]['id'] if r else '')")"
  [ -n "$CF_ZONE_ID" ] || {
    echo "ERROR: the token cannot see zone ${ZONE}. Check its Zone Resources." >&2
    return 1
  }
  echo "      zone ${ZONE} (${CF_ZONE_ID})"
  for h in $hosts; do
    cf_ensure_cname "$h" "$host" || fail=1
  done
  [ "$fail" -eq 0 ] || return 1

  # Prove it at the source of truth, not at a resolver that may be caching
  # the record's absence. With retries: the API acknowledging a create and the
  # record being answerable at the nameservers are seconds apart, and asking
  # exactly once in that gap prints an empty line that reads like a failure.
  ns="$(dig +short NS "$ZONE" 2>/dev/null | head -1)"
  echo ""
  echo "      verifying at ${ns:-the zone}..."
  local h ans sys code alb_ip i
  # The ALB's current address, used to test HTTPS without involving DNS at all.
  alb_ip="$(dig +short A "$host" @1.1.1.1 2>/dev/null | head -1)"

  printf '      %-24s %-10s %-10s %s\n' "host" "zone" "your-dns" "https"
  for h in $hosts; do
    ans=""
    for i in 1 2 3 4 5 6; do
      ans="$(dig +short CNAME "$h" ${ns:+@"$ns"} 2>/dev/null | head -1)"
      [ -n "$ans" ] && break
      sleep 5
    done

    # The resolver THIS MACHINE actually uses -- which is what curl and a
    # browser use, and which is not necessarily 1.1.1.1. A record that is live
    # at the zone but absent here is a stale negative cache on the client side,
    # not a platform fault, and the two need telling apart.
    sys="$(dig +short CNAME "$h" 2>/dev/null | head -1)"

    # And the question that actually matters: does the platform serve this
    # hostname? --resolve pins the address so DNS cannot mask the answer.
    if [ -n "$alb_ip" ]; then
      code="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 10 \
        --resolve "${h}:443:${alb_ip}" "https://${h}/" 2>/dev/null || echo "---")"
    else
      code="?"
    fi

    printf '      %-24s %-10s %-10s %s\n' "$h" \
      "$([ -n "$ans" ] && echo ok || echo MISSING)" \
      "$([ -n "$sys" ] && echo ok || echo stale)" \
      "$code"
  done

  cat <<'EOF'

      zone      the record at the authoritative nameserver -- the truth
      your-dns  the resolver this machine uses; `stale` means it still
                remembers the name not existing. Nothing to fix on the
                platform: it expires on its own within 30 minutes, or
                  sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder
      https     the ALB answering for that hostname, DNS bypassed. 2xx/3xx
                means the platform is serving it correctly regardless of what
                the two DNS columns say. 401/403 is also fine -- it means the
                request reached the application.
EOF
}

case "$MODE" in
  dns)
    HOST="$(alb_hostname)"
    [ -n "$HOST" ] || { echo "The ALB has no hostname yet. Wait a minute and retry." >&2; exit 1; }
    echo "ALB hostname: ${HOST}"
    echo ""
    echo "Applying DNS records through the Cloudflare API..."
    cf_apply_dns "$HOST" && exit 0
    echo "" >&2
    echo "API path failed; falling back to the import file." >&2
    write_dns_records_file "$HOST"
    echo "Wrote ${RECORDS_FILE}:"
    grep -v '^;' "$RECORDS_FILE" | grep -v '^$' | awk '{print "  " $1}'
    cat <<EOF

Import it: Cloudflare -> nopega.net -> DNS -> Records -> Import
           Leave "Proxy imported DNS records" UNCHECKED.

DNS only, not proxied, for two separate reasons:

  1. The ALB's certificate is issued for these exact hostnames. Proxying puts
     Cloudflare's certificate in front instead, and the connection Cloudflare
     makes to the ALB is a second TLS session that has to be configured
     correctly or it fails as a 5xx that looks like the origin is down.

  2. Cloudflare's free plan caps request bodies at 100 MB. That is invisible
     for Airflow, and fatal for pushing a container image layer -- which is
     why Harbor will use this ALB rather than a tunnel.

Do NOT delete the ACM validation CNAMEs already in the zone. ACM re-reads them
to renew the certificate automatically.
EOF
    exit 0
    ;;

  verify)
    echo "=== ingress objects ==="
    kubectl get ingress -A -o wide 2>/dev/null | grep -E 'NAME|public' || echo "  none"
    echo ""
    echo "=== ALB ==="
    HOST="$(alb_hostname)"
    if [ -n "$HOST" ]; then
      echo "  ${HOST}"
      LB_ARN="$(aws elbv2 describe-load-balancers --region "$REGION" \
        --query "LoadBalancers[?DNSName=='${HOST}'].LoadBalancerArn | [0]" --output text 2>/dev/null)"
      echo ""
      echo "=== target group health (this is what decides 503 vs 200) ==="
      # An ALB with healthy pods but unhealthy targets returns 503 and looks
      # like an application outage. Check here before debugging the app.
      for TG in $(aws elbv2 describe-target-groups --region "$REGION" \
            --load-balancer-arn "$LB_ARN" --query 'TargetGroups[].TargetGroupArn' \
            --output text 2>/dev/null); do
        echo "  $(basename "$TG")"
        aws elbv2 describe-target-health --region "$REGION" --target-group-arn "$TG" \
          --query 'TargetHealthDescriptions[].[Target.Id,TargetHealth.State,TargetHealth.Reason]' \
          --output text 2>/dev/null | sed 's/^/    /'
      done
      echo ""
      echo "=== security group ingress rules (who can reach it) ==="
      for SG in $(aws elbv2 describe-load-balancers --region "$REGION" \
            --load-balancer-arns "$LB_ARN" --query 'LoadBalancers[0].SecurityGroups' \
            --output text 2>/dev/null); do
        aws ec2 describe-security-groups --region "$REGION" --group-ids "$SG" \
          --query 'SecurityGroups[0].IpPermissions[].{port:FromPort,cidrs:IpRanges[].CidrIp}' \
          --output json 2>/dev/null | sed 's/^/  /'
      done
    else
      echo "  not created yet"
      echo ""
      echo "  If this stays empty, the controller is refusing to reconcile."
      echo "  Its log says why -- most often a missing subnet tag:"
      echo "    kubectl logs -n kube-system -l app.kubernetes.io/name=aws-load-balancer-controller --tail=40"
    fi
    echo ""
    echo "=== does DNS point at it yet? ==="
    for h in airflow.nopega.net trino.nopega.net harbor.nopega.net grafana.nopega.net argocd.nopega.net prometheus.nopega.net; do
      printf '  %-22s -> %s\n' "$h" "$(dig +short CNAME "$h" 2>/dev/null | head -1)"
    done
    exit 0
    ;;

  delete)
    kubectl delete -f <(sed -e "s|__CERT_ARN__|placeholder|" -e "s|__INBOUND_CIDRS__|0.0.0.0/32|" "$MANIFEST") --ignore-not-found
    cat <<EOF

Ingress removed, and with it the ALB -- the controller deletes the load
balancer when the last Ingress in the group goes away.

The ACM certificate and its validation CNAMEs are untouched, so recreating
this later does not mean redoing DNS validation.
EOF
    exit 0
    ;;
esac

# ---------------------------------------------------------------------------
# 1. Certificate must be ISSUED. Applying with a PENDING_VALIDATION ARN
#    creates an ALB whose listener has a certificate that cannot serve traffic.
# ---------------------------------------------------------------------------
echo "[1/5] Certificate..."
REQUIRED_HOSTS="trino.nopega.net airflow.nopega.net harbor.nopega.net grafana.nopega.net argocd.nopega.net prometheus.nopega.net"

# Every ISSUED certificate for this domain, not just the first one.
#
# `| [0]` was wrong here and only became visibly wrong when grafana was added.
# Adding a hostname means requesting a SECOND certificate -- ACM cannot extend
# an issued one -- so for the period between the new certificate being issued
# and the old one being deleted, there are two, and [0] picks whichever the API
# happens to return first. Half the time that is the old certificate, which is
# ISSUED, valid, and missing a name. The ALB would then serve grafana with a
# certificate that does not cover it: a browser TLS warning on one hostname,
# from a script that reported success.
CERT_ARN=""
CERT_FALLBACK=""
for arn in $(aws acm list-certificates --region "$REGION" \
  --certificate-statuses ISSUED \
  --query "CertificateSummaryList[?DomainName=='${PRIMARY_DOMAIN}'].CertificateArn" \
  --output text 2>/dev/null | tr '\t' '\n' | grep -v '^None$' || true); do
  [ -n "$CERT_FALLBACK" ] || CERT_FALLBACK="$arn"
  names="$(aws acm describe-certificate --region "$REGION" --certificate-arn "$arn" \
    --query 'Certificate.SubjectAlternativeNames' --output text 2>/dev/null | tr '\t\n' '  ')"
  ok=1
  for h in $REQUIRED_HOSTS; do
    case " $names " in *" $h "*) ;; *) ok=0 ;; esac
  done
  [ "$ok" -eq 1 ] && { CERT_ARN="$arn"; break; }
done

# Nothing covers everything: fall through to the coverage check below with the
# best candidate, so the error names the missing host rather than saying no
# certificate exists.
[ -n "$CERT_ARN" ] || CERT_ARN="$CERT_FALLBACK"

if [ -z "$CERT_ARN" ]; then
  echo "ERROR: no ISSUED certificate for ${PRIMARY_DOMAIN}." >&2
  echo "       Current state:" >&2
  "$SCRIPT_DIR/01_request_acm_certificate_prod.sh" verify >&2 || true
  echo "" >&2
  echo "       Wait for status ISSUED before applying the Ingress." >&2
  exit 1
fi

# Confirm the certificate actually covers all three names. A certificate can be
# ISSUED for a subset, and the mismatch only appears as a browser TLS warning
# on the one hostname that was left out.
# `--output text` separates list items with TABS, not spaces. The membership
# test below matches on space-delimited words, so without this the check fails
# for every name after the first -- reporting that a certificate does not cover
# a domain it visibly does, which is worse than not checking at all.
COVERED="$(aws acm describe-certificate --region "$REGION" --certificate-arn "$CERT_ARN" \
  --query 'Certificate.SubjectAlternativeNames' --output text | tr '\t\n' '  ')"
echo "      ISSUED, covers: ${COVERED}"
# grafana was added after the first certificate was issued, and ACM cannot add
# a name to one. If this check fails, the fix is
# ./01_request_acm_certificate_prod.sh renew -- not editing this list.
for h in $REQUIRED_HOSTS; do
  case " $COVERED " in
    *" $h "*) ;;
    *) echo "ERROR: certificate does not cover ${h}." >&2; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# 2. Source CIDRs.
# ---------------------------------------------------------------------------
echo "[2/5] Allowed source ranges..."
if [ -n "$MODE" ]; then
  INBOUND_CIDRS="$MODE"
  printf '%s' "$INBOUND_CIDRS" > "$CIDR_FILE"
elif [ -f "$CIDR_FILE" ]; then
  INBOUND_CIDRS="$(cat "$CIDR_FILE")"
else
  cat >&2 <<EOF
ERROR: no source CIDR given and none saved.

  This deliberately has no default. A default of 0.0.0.0/0 would put Airflow
  and Trino on the open internet the moment this script is run, protected by
  nothing but their login forms -- and it would do so silently.

  Find your current public address:

    curl -s https://checkip.amazonaws.com

  Then pass it as a /32:

    $0 203.0.113.5/32

  Several ranges are allowed, comma-separated:

    $0 203.0.113.5/32,198.51.100.0/24

  Note that a home connection's address usually changes. When it does, the
  symptom is a connection that times out rather than one that is refused --
  re-run this script with the new address.
EOF
  exit 1
fi

if [ "$INBOUND_CIDRS" = "0.0.0.0/0" ]; then
  echo "      WARNING: 0.0.0.0/0 -- the entire internet can reach the ALB."
  echo "      Trino has password auth and Airflow has its login form, but this"
  echo "      removes the network layer entirely. Continuing in 5s; Ctrl-C to stop."
  sleep 5
fi

# The cluster's own NAT gateway address, added automatically and NOT saved to
# .inbound-cidrs.
#
# WHY THIS IS NEEDED
# -------------------
# The nodes are in private subnets. When a node pulls an image from
# harbor.nopega.net it resolves the PUBLIC ALB address, leaves the VPC through
# the NAT gateway, and arrives at the ALB from the NAT's elastic IP -- not from
# whatever address a human put in .inbound-cidrs. With only the human's address
# allowed, the pull fails as:
#
#   failed to do request: Head "https://harbor.nopega.net/v2/.../manifests/...":
#   dial tcp <alb-ip>:443: i/o timeout
#
# A timeout, not a 403, because a security group drops the packet rather than
# rejecting it. Nothing in that message mentions security groups, and the
# obvious reading -- that the pull credential is wrong -- is wrong.
#
# WHY IT IS DERIVED AND NOT SAVED
# ---------------------------------
# The NAT gateway's address changes if the gateway is ever replaced (a VPC
# rebuild, an AZ migration). A value written into .inbound-cidrs once would
# then be stale, and the failure would look exactly like the one above with no
# hint that the saved file is the cause. Re-deriving it on every run means the
# file only ever holds addresses a human chose.
CLUSTER_VPC="$(aws eks describe-cluster --name "$CLUSTER_NAME" --region "$REGION" \
  --query 'cluster.resourcesVpcConfig.vpcId' --output text 2>/dev/null || true)"
NAT_IPS=""
if [ -n "$CLUSTER_VPC" ] && [ "$CLUSTER_VPC" != "None" ]; then
  # Scoped to this VPC: an account with other VPCs would otherwise punch holes
  # for NAT gateways that have nothing to do with this cluster.
  NAT_IPS="$(aws ec2 describe-nat-gateways --region "$REGION" \
    --filter "Name=vpc-id,Values=${CLUSTER_VPC}" "Name=state,Values=available" \
    --query 'NatGateways[].NatGatewayAddresses[].PublicIp' --output text 2>/dev/null || true)"
fi

if [ -n "$NAT_IPS" ]; then
  for ip in $NAT_IPS; do
    case ",$INBOUND_CIDRS," in
      *",${ip}/32,"*) ;;                                   # already present
      *) INBOUND_CIDRS="${INBOUND_CIDRS},${ip}/32" ;;
    esac
  done
  echo "      + NAT gateway $(printf '%s' "$NAT_IPS" | tr '\t' ' ') (so nodes can pull from Harbor)"
else
  echo "      WARNING: no NAT gateway found in ${CLUSTER_VPC:-unknown VPC}."
  echo "               If the nodes are in private subnets, image pulls from"
  echo "               harbor.nopega.net will time out."
fi

echo "      ${INBOUND_CIDRS}"

# ---------------------------------------------------------------------------
# 3. Backends must exist. The controller creates an ALB with an empty target
#    group for a missing Service and reports nothing obvious.
# ---------------------------------------------------------------------------
echo "[3/5] Backend services..."
kubectl get svc airflow-api-server -n airflow >/dev/null 2>&1 \
  || { echo "ERROR: Service airflow-api-server not found in namespace airflow." >&2; exit 1; }
kubectl get svc trino -n data-platform >/dev/null 2>&1 \
  || { echo "ERROR: Service trino not found in namespace data-platform." >&2; exit 1; }
kubectl get svc harbor -n harbor >/dev/null 2>&1 \
  || { echo "ERROR: Service harbor not found in namespace harbor." >&2; exit 1; }
echo "      airflow-api-server, trino, harbor"

# Trino must already require a password. Applying this while authenticationType
# is empty publishes an unauthenticated query engine.
AUTH="$(kubectl get cm -n data-platform -o yaml 2>/dev/null \
  | grep -c 'http-server.authentication.type=PASSWORD' || true)"
if [ "$AUTH" -eq 0 ]; then
  cat >&2 <<EOF
ERROR: Trino does not appear to have PASSWORD authentication enabled.

  Exposing it now would put an unauthenticated query engine on the internet,
  with read and write access to every Iceberg table.

    cd ../../../set_up_component/02_trino_prod
    ./02_create_trino_auth_secrets_prod.sh
    ./03_install_trino_prod.sh
EOF
  exit 1
fi
echo "      Trino requires a password"

# ---------------------------------------------------------------------------
echo "[4/5] Applying..."
sed -e "s|__CERT_ARN__|${CERT_ARN}|g" \
    -e "s|__INBOUND_CIDRS__|${INBOUND_CIDRS}|g" \
    "$MANIFEST" | kubectl apply -f -

echo "[5/5] Waiting for the controller to provision the ALB (up to 4 min)..."
for i in $(seq 1 48); do
  HOST="$(alb_hostname)"
  [ -n "$HOST" ] && break
  sleep 5
done

if [ -z "${HOST:-}" ]; then
  cat >&2 <<EOF

The Ingress was accepted but no ALB hostname appeared.

Almost always a subnet tagging problem: the controller needs public subnets
tagged kubernetes.io/role/elb=1 to place an internet-facing load balancer.
Its log names the exact cause:

  kubectl logs -n kube-system -l app.kubernetes.io/name=aws-load-balancer-controller --tail=40
EOF
  exit 1
fi

write_dns_records_file "$HOST"

cat <<EOF

ALB provisioned: ${HOST}

Wrote the Cloudflare import file from the hosts this manifest actually routes:

  ${RECORDS_FILE}

$(grep -v '^;' "$RECORDS_FILE" | grep -v '^$' | awk '{print "  " $1}')

Import it: Cloudflare -> nopega.net -> DNS -> Records -> Import
           Leave "Proxy imported DNS records" UNCHECKED.

Then, once DNS propagates:

  curl -sI https://trino.nopega.net/v1/info
  curl -sI https://airflow.nopega.net

Give the target groups a minute before judging a 503 -- targets start
unhealthy and need two consecutive passing checks 30s apart.

  ./02_apply_public_ingress_prod.sh verify
EOF
